version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: voting-system-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - voting-network

  backend:
    build: ./backend
    container_name: voting-system-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/voting_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - voting-network

  db:
    image: postgres:14
    container_name: voting-system-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=voting_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - voting-network

networks:
  voting-network:
    driver: bridge

volumes:
  postgres_data: